### ISSUE TITLE
How is APFS support supposed to work with mmls and fls?

### ISSUE THREAD

**Issue by joachimmetz** [blackbagtech/sleuthkit-APFS#2]
APFS support using the mmls and fls does not appear to be working for me unless this forks deviates from the original project?

```
mmls apfs_single_volume_case_sensitive.dmg 
GUID Partition Table (EFI)
Offset Sector: 0
Units are in 512-byte sectors

      Slot      Start        End          Length       Description
000:  Meta      0000000000   0000000000   0000000001   Safety Table
001:  -------   0000000000   0000000039   0000000040   Unallocated
002:  Meta      0000000001   0000000001   0000000001   GPT Header
003:  Meta      0000000002   0000000033   0000000032   Partition Table
004:  000       0000000040   0000008151   0000008112   disk image
005:  -------   0000008152   0000008191   0000000040   Unallocated
```

**How do I view the APFS volumes in the APFS container?**
```
mmls -o 40 apfs_single_volume_case_sensitive.dmg 
Cannot determine partition type
```

**How do I view the contents of an APFS volumes/file system?**
```
fls -o 40 apfs_single_volume_case_sensitive.dmg 
Cannot determine file system type
```

**To confirm that this image has an APFS container and volume:**
```
fsapfsinfo -o $(( 40 * 512 )) apfs_single_volume_case_sensitive.dmg
fsapfsinfo 20181219

Apple File System (APFS) information:

Container information:
	Identifier		: 2d11f56f-b439-4db5-b288-f2a53953758b
	Number of volumes	: 1

Volume: 1 information:
	Identifier		: 7ddb6f18-07e6-4b70-9990-f0249e4de926
	Name			: SingleVolume

```

```
fsapfsinfo -f1 -H -o $(( 40 * 512 )) apfs_single_volume_case_sensitive.dmg
fsapfsinfo 20181219

Apple File System (APFS) information:

File system hierarchy:
/{7ddb6f18-07e6-4b70-9990-f0249e4de926}/
/{7ddb6f18-07e6-4b70-9990-f0249e4de926}/.fseventsd
/{7ddb6f18-07e6-4b70-9990-f0249e4de926}/.fseventsd/fseventsd-uuid
/{7ddb6f18-07e6-4b70-9990-f0249e4de926}/.fseventsd/00000000007877c8
/{7ddb6f18-07e6-4b70-9990-f0249e4de926}/.fseventsd/00000000007877c7
```

**Installation:**
```
git clone https://github.com/blackbagtech/sleuthkit-APFS.git
cd sleuthkit-APFS
./bootstrap
./configure
...
Building:
   afflib support:                        no
   libewf support:                        no
   zlib support:                          yes
   openssl support:                       yes

   libvhdi support:                       no
   libvmdk support:                       no
   postgresql support:                    no
Features:
   Java/JNI support:                      no
   Multithreading:                        yes

make >/dev/null

...
apfs_compat.cpp: In member function ‘uint8_t APFSFSCompat::load_attrs(TSK_FS_FILE*) const’:
apfs_compat.cpp:843:28: warning: comparison of integer expressions of different signedness: ‘const TSK_OFF_T’ {aka ‘const long int’} and ‘long unsigned int’ [-Wsign-compare]
     if (decmpfs_attr->size < sizeof(DECMPFS_DISK_HEADER)) {
         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
apfs_compat.cpp: In function ‘uint8_t tsk_apfs_list_snapshots(TSK_FS_INFO*, apfs_snapshot_list**)’:
apfs_compat.cpp:1333:22: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<APFSFileSystem::<unnamed struct> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
   for (auto i = 0; i < snapshots.size(); i++) {
                    ~~^~~~~~~~~~~~~~~~~~
apfs_compat.cpp: In function ‘uint8_t tsk_apfs_fsstat(TSK_FS_INFO*, apfs_fsstat_info*)’:
apfs_compat.cpp:405:10: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 128 equals destination size [-Wstringop-truncation]
   strncpy(info->name, vol.name().c_str(), sizeof(info->name));
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
apfs_compat.cpp:407:10: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 256 equals destination size [-Wstringop-truncation]
   strncpy(info->password_hint, vol.password_hint().c_str(),
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           sizeof(info->password_hint));
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
apfs_compat.cpp:409:10: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 32 equals destination size [-Wstringop-truncation]
   strncpy(info->formatted_by, vol.formatted_by().c_str(),
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           sizeof(info->formatted_by));
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
```

**Comment by jtsylve** [comment]
In order to parse an APFS volume with `fls` you must first use the new `pstat` utility to enumerate the volumes and get the superblock number of your volume of choice to pass to `fls`.

Using your example, you'd do something like this to enumerate the volumes and learn the superblock of your volume of choice (there can be more than one).

```
pstat -o 40 apfs_single_volume_case_sensitive.dmg
```

After that you can use `fls`, `fsstat`, `istat`, & `icat` as normal by passing the superblock number to a new `-B` flag.

```
fls -o 40 -B <superblocknumer> apfs_single_volume_case_sensitive.dmg
```

A Few other notes: 

If the volume is encrypted, there's also a `-k` flag for the password or recovery key.  `fsstat` will also give you the XID of any snapshots.  You can parse the snapshot with the tools by passing that SID to a new `-s` flag.

**Comment by jtsylve** [comment]
Thanks for the compiler warnings.  I'll clean those up.  The above also needs to be documented somewhere other than the youtube Video from the BlackBag blogpost.  I'll work on that.

**Comment by joachimmetz** [comment]
Why not integrated in the existing tooling?

**Comment by jtsylve** [comment]
I don't understand the question.  The only new tool is `pstat` which is a new tool to give information about the pooled storage layer (which didn't exist before).

**Comment by joachimmetz** [comment]
OK pstat seems to work on this image, I'll file another issue seeing it is segfaulting on another image.

```
pstat -o 40  apfs_single_volume.dmg 
POOL CONTAINER INFORMATION
--------------------------------------------

Container 93584bd3-a0da-4427-9540-6ba6034f3150
==============================================
Type: APFS

NX Block Number: 0
NX oid: 1
NX xid: 5
Checkpoint Descriptor Block: 1

Capacity Ceiling (Size): 4153344 B
Capacity In Use:         462848 B
Capacity Available:      3690496 B

Block Size:            4096 B
Number of Blocks:      1014
Number of Free Blocks: 901
|
+-> Volume 3f29cd7d-e1b8-406e-9b3c-3b36b2086ccd
|   ===========================================
|   APSB Block Number: 110
|   APSB oid: 1026
|   APSB xid: 5
|   Name (Role): TestVolume (No specific role)
|   Capacity Consumed: 32768 B
|   Capacity Reserved: None
|   Capacity Quota: None
|   Case Sensitive: No
|   Encrypted: No
|   Formatted by: newfs_apfs (748.77.8)
|
|   Created: 2018-09-07 16:07:51.179715086 (CEST)
|   Changed: 2018-09-07 16:08:12.446039094 (CEST)
|
|   Unmount Logs
|   ------------
|   Timestamp                            Log String
|   2018-09-07 16:08:12.467639788 (CEST)  apfs_kext compiled @ Jun 21 201
|
|   Root Files
|   -------------
|  [      16] .fseventsd
|
+-> Unallocated Container Blocks
|   ============================
|   0x00000071-0x000003f5
```

> I don't understand the question. 

What I mean why have this separate pooling layer tool? also why the term pooling? Isn't this yet another volume system like CoreStorage and LVM?

**Comment by jtsylve** [comment]
Adding a pooled storage layer to TSK was first proposed in [this paper](https://www.sciencedirect.com/science/article/pii/S1742287617301901).  This was implemented with that in mind.  The ZFS and BTRFS implementations from the same authors are being ported to use the layer I've created here, so it's meant for more than just APFS.

Once you start having to take into account pooled storage that is built from multiple physical partitions (like with fusion drives), sticking it into the VS layer starts to get a bit hackish

**Comment by joachimmetz** [comment]
> sticking it into the VS layer starts to get a bit hackish

I see so basically this is the next gen of the TSK volume system layer, that will support multi disk/volume images. I personally would have reserved the term pooling just for bundling of one or more disks/volumes and have the volume system layer deal with the logical view on top of that. But understand that current model of libtsk is limiting.

Would be interesting to know how the new pooling model will deal with more complex models:
5x partitioned disks
every disk has 1x LUKS encrypted volume
on top of the LUKS encrypted volume is a SW raid 5
inside the raid logical volume is an LVM
inside the LVM are 3 volumes
... etc ...

**Comment by joachimmetz** [comment]
@jtsylve pstat works but fls segfaults
```
fls -B 110 -o 40 apfs_single_volume_case_sensitive.dmg 
Segmentation fault (core dumped)
```

**Comment by joachimmetz** [comment]
BTW if you want copies of the images I'm using you can create these with https://github.com/dfirlabs/apfs-specimens

**Comment by jtsylve** [comment]
I'm not seeing a segfault.  Can you upload the exact image you're using somewhere?
```
$ ./tools/pooltools/pstat -o 40 ~/Desktop/apfs_single_volume.dmg  
POOL CONTAINER INFORMATION
--------------------------------------------

Container ec48612f-7cd3-4fbb-b4f3-8f5028a3f04b
==============================================
Type: APFS

NX Block Number: 0
NX oid: 1
NX xid: 4
Checkpoint Descriptor Block: 7

Capacity Ceiling (Size): 4153344 B
Capacity In Use:         434176 B
Capacity Available:      3719168 B

Block Size:            4096 B
Number of Blocks:      1014
Number of Free Blocks: 908
|
+-> Volume 97b7d55c-9866-467a-883f-f4a30847a6eb
|   ===========================================
|   APSB Block Number: 103
|   APSB oid: 1026
|   APSB xid: 4
|   Name (Role): SingleVolume (No specific role)
|   Capacity Consumed: 32768 B
|   Capacity Reserved: None
|   Capacity Quota: None
|   Case Sensitive: No
|   Encrypted: No
|   Formatted by: diskmanagementd (945.230.6)
|
|   Created: 2018-12-20 09:23:56.549682795 (CST)
|   Changed: 2018-12-20 09:23:58.683414672 (CST)
|
|   Unmount Logs
|   ------------
|   Timestamp                            Log String
|   2018-12-20 09:23:58.705035432 (CST)  apfs_kext (945.230.6)
|
|   Root Files
|   -------------
|  [      22] symboliclink1
|  [      18] testdir1
|  [      26] nfkd_3⁄4
|  [      19] hardlink1
|  [      24] nfd_téstfilè
|  [      16] .fseventsd
|  [      25] nfd_¾
|  [      27] case_folding_µ
|  [      23] nfc_téstfilè
|
+-> Unallocated Container Blocks
|   ============================
|   0x0000006a-0x000003f5
```
```
$ ./tools/fstools/fls -B 103 -o 40 ~/Desktop/apfs_single_volume.dmg 
l/l 22:	symboliclink1
d/d 18:	testdir1
r/r 26:	nfkd_3⁄4
r/r 19:	hardlink1
r/r 24:	nfd_téstfilè
d/d 16:	.fseventsd
r/r 25:	nfd_¾
r/r 27:	case_folding_µ
r/r 23:	nfc_téstfilè
```

**Comment by joachimmetz** [comment]
Let me get you a back trace instead

```
gdb --args fls -B 110 -o 40 apfs_single_volume_case_sensitive.dmg 
GNU gdb (GDB) Fedora 8.2-5.fc29
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./tools/fstools/fls...done.
(gdb) r
Starting program: fls -B 110 -o 40 apfs_single_volume_case_sensitive.dmg
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:313
313		movl	%ecx, -4(%rdi,%rdx)
Missing separate debuginfos, use: dnf debuginfo-install libgcc-8.2.1-5.fc29.x86_64 libstdc++-8.2.1-5.fc29.x86_64 openssl-libs-1.1.1-3.fc29.x86_64 sqlite-libs-3.24.0-2.fc29.x86_64 zlib-1.2.11-14.fc29.x86_64
(gdb) bt
#0  __memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:313
#1  0x000000000040fb5c in std::char_traits<char>::copy (__n=<optimized out>, __s2=0x7fffffffbbe0 "root", __s1=<optimized out>) at /usr/include/c++/8/bits/char_traits.h:350
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=<optimized out>, __s=0x7fffffffbbe0 "root", __d=<optimized out>) at /usr/include/c++/8/bits/basic_string.h:340
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy (__n=<optimized out>, __s=0x7fffffffbbe0 "root", __d=<optimized out>) at /usr/include/c++/8/bits/basic_string.h:335
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (__str=..., this=0x4d0a90) at /usr/include/c++/8/bits/basic_string.h:751
#5  APFSJObject::operator= (this=0x4d09d0) at apfs_fs.hpp:7
#6  APFSFSCompat::file_add_meta (this=<optimized out>, fs_file=0x4d0890, addr=2) at apfs_compat.cpp:547
#7  0x0000000000422ec4 in tsk_fs_file_open_meta (a_fs=a_fs@entry=0x4cda38, a_fs_file=a_fs_file@entry=0x0, a_addr=a_addr@entry=2) at fs_file.c:128
#8  0x0000000000409a29 in APFSFSCompat::dir_open_meta (this=<optimized out>, a_fs_dir=0x7fffffffbca8, inode_num=2) at apfs_compat.cpp:472
#9  0x00000000004217d0 in tsk_fs_dir_open_meta (a_fs=<optimized out>, a_addr=<optimized out>) at fs_dir.c:290
#10 0x0000000000421939 in tsk_fs_dir_walk_lcl (a_fs=a_fs@entry=0x4cda38, a_dinfo=a_dinfo@entry=0x7fffffffbd40, a_addr=a_addr@entry=2, 
    a_flags=a_flags@entry=(TSK_FS_DIR_WALK_FLAG_ALLOC | TSK_FS_DIR_WALK_FLAG_UNALLOC), a_action=a_action@entry=0x41f150 <print_dent_act>, a_ptr=a_ptr@entry=0x7fffffffd1a0) at fs_dir.c:556
#11 0x0000000000422041 in tsk_fs_dir_walk (a_fs=0x4cda38, a_addr=2, a_flags=(TSK_FS_DIR_WALK_FLAG_ALLOC | TSK_FS_DIR_WALK_FLAG_UNALLOC), a_action=0x41f150 <print_dent_act>, a_ptr=0x7fffffffd1a0) at fs_dir.c:817
#12 0x000000000042240d in tsk_fs_dir_walk (a_fs=a_fs@entry=0x4cda38, a_addr=<optimized out>, a_flags=a_flags@entry=(TSK_FS_DIR_WALK_FLAG_ALLOC | TSK_FS_DIR_WALK_FLAG_UNALLOC), 
    a_action=a_action@entry=0x41f150 <print_dent_act>, a_ptr=a_ptr@entry=0x7fffffffd1a0) at fs_dir.c:792
#13 0x000000000041f3b8 in tsk_fs_fls (fs=fs@entry=0x4cda38, lclflags=lclflags@entry=(TSK_FS_FLS_FILE | TSK_FS_FLS_DIR), inode=<optimized out>, 
    flags=flags@entry=(TSK_FS_DIR_WALK_FLAG_ALLOC | TSK_FS_DIR_WALK_FLAG_UNALLOC), tpre=<optimized out>, skew=skew@entry=0) at fls_lib.c:262
#14 0x0000000000406eee in main (argc=<optimized out>, argv1=<optimized out>) at fls.cpp:39
```

**Comment by jtsylve** [comment]
For whatever reason, the crash was only presenting itself on certain versions Linux.  It should be fixed now.

**Comment by jtsylve** [comment]
Keeping this open until we add some documentation on the new flags.

**Comment by joachimmetz** [comment]
Confirmed 0948053 fixes the segfault.
